### PR TITLE
Fix lost planet cache

### LINKED ISSUE #219: Federation lost planet algorithm glitch
https://www.boardgamers.space/game/Blue-list-835 There was an alliance building issue on end of the game experienced by terrans.   Basically, I wanted to build a federation using the shortest way, which was fine but then the shortest path was blocked by the lost planet of the other player. I was like ''Okey, I will use one more satelite to do it around'' But the game kept suggesting shortest path going through the lost planet and then if I tried it said that I can not put it there due to that lost planet. And when I custom build the satelite road it said that I must use shortest path and in the sugested road was again the lost planet on which the satelite can not be put. It wouldn't change outcome of the game but still was annoying that glitch caused the block to be way stronger than should have been

### PR DESCRIPTION
**Pull request by Zevenberge**
Fixes #219

### CODE REVIEW

File: src/player.ts [hunk 1]
```diff
@@ -820,6 +820,14 @@ export default class Player extends EventEmitter {
     return 0;
   }
 
+  clearFederationCacheIfLostPlanetIsInTheWay(hexOfLostPlanet: GaiaHex) {
```
Comment (coyotte508) [inline src/player.ts:823]: To make it more generic - a name like `clearFederationCacheIfIncludesHex` or just `handleNewPlanet` / `notifyOfNewPlanet`. 

In case a future extension allows placing a new planet on the map of any kind, or a new kind of federation blocker.

**Review by coyotte508 — CHANGES_REQUESTED** [review]

**Comment by coyotte508** [comment]
Very clean PR, thank you!
